################################################################################
# Testing plotting functions
################################################################################

# HELPER FUNCTIONS
################################################################################
#' Suppress plot-related warnings, messages, and graphics output (testing utility)
#'
#' Internal helper used in unit tests to silence warnings, messages, and
#' graphics output generated by plotting functions. Prevents creation of
#' Rplots.pdf and other unwanted plot files during testing.
#'
#' @param expr An R expression to evaluate.
#'
#' @return The result of evaluating \code{expr}, with warnings, messages,
#'   and graphics output suppressed.
#'
#' @keywords internal
suppress_plot_warnings <- function(expr) {
  # Store original working directory
  orig_wd <- getwd()

  # Create temporary directory for any file outputs
  temp_dir <- tempdir()
  temp_test_dir <- file.path(temp_dir, paste0("ninetails_test_", Sys.getpid()))
  dir.create(temp_test_dir, showWarnings = FALSE, recursive = TRUE)

  # Ensure cleanup happens even if expr fails
  on.exit({
    # Reset working directory
    setwd(orig_wd)

    # Clean up any graphics devices we may have opened
    while(length(grDevices::dev.list()) > 0) {
      try(grDevices::dev.off(), silent = TRUE)
    }

    # Remove temporary test directory
    unlink(temp_test_dir, recursive = TRUE, force = TRUE)
  }, add = TRUE)

  # Change to temporary directory to catch any file outputs
  setwd(temp_test_dir)

  # Open a null graphics device to capture plot output
  grDevices::png(filename = file.path(temp_test_dir, "null_plot.png"),
                 width = 1, height = 1)

  # Execute expression with all output suppressed
  result <- suppressWarnings(suppressMessages(expr))

  return(result)
}


#' Generate dummy nanopolish_qc summary data (testing utility)
#'
#' Internal helper function used in unit tests to create synthetic
#' QC summary tables. Produces either aggregated or per-sample
#' dummy read counts across predefined QC categories.
#'
#' @param grouped Logical. If \code{FALSE}, returns an aggregated
#'   summary table. If \code{TRUE}, returns per-sample summaries.
#'
#' @return A \code{data.frame} containing QC tags and dummy read counts.
#'
#' @keywords internal
create_test_processing_info <- function(grouped = FALSE) {
  qc_tags <- c("PASS",
               "ADAPTER",
               "SUFFCLIP",
               "NOREGION",
               "READ_FAILED_LOAD")

  if (!grouped) {
    data.frame(qc_tag = qc_tags,
               n = c(500, 50, 30, 15, 5),
               stringsAsFactors = FALSE)
  } else {
    rbind(
      data.frame(sample_name = "WT_1",
                 qc_tag = qc_tags,
                 n = c(250, 25, 15, 8, 2),
                 stringsAsFactors = FALSE),
      data.frame(sample_name = "KO_1",
                 qc_tag = qc_tags,
                 n = c(300, 30, 20, 10, 4),
                 stringsAsFactors = FALSE)
    )
  }
}


#' Create minimal class_data (QCF variant)
#'
#' Generates a test data frame mimicking a Guppy/nanopolish pipeline
#' with QCF reads, without BAC or UNM annotations.
#'
#' @param grouped Logical; if TRUE, adds a `sample_name` column
#'   splitting reads into WT and KO groups.
#'
#' @return A data.frame containing simulated read classification data.
#'
#' @keywords internal
# Guppy/nanopolish pipeline: has QCF, no BAC, no UNM
make_class_data_qcf <- function(grouped = FALSE) {

  base <- data.frame(readname = paste0("read_", 1:6),
                     contig = "beta_gal",
                     polya_length = c(50, 30, 8, 45, 20, 55),
                     qc_tag = c("PASS", "PASS", "PASS", "PASS", "PASS", "ADAPTER"),
                     class = c("decorated", "blank", "unclassified", "blank",
                              "unclassified", "unclassified"),
                     comments = c("YAY", "MAU", "IRL", "MPU", "MPU", "QCF"),
                     stringsAsFactors = FALSE)

  if (grouped) {
    base$sample_name <- c(rep("WT", 3), rep("KO", 3))
  }
  base
}


#' Create minimal class_data (BAC variant)
#'
#' Generates a test data frame mimicking a Dorado DRS pipeline
#' with BAC reads, without UNM annotations.
#'
#' @param grouped Logical; if TRUE, adds a `sample_name` column
#'   splitting reads into WT and KO groups.
#'
#' @return A data.frame containing simulated read classification data.
#'
#' @keywords internal
make_class_data_bac <- function(grouped = FALSE) {

  base <- data.frame(readname = paste0("read_", 1:6),
                     contig = "beta_gal",
                     polya_length = c(50, 30, 8, 45, 20, 55),
                     qc_tag = c(60L, 60L, 60L, 60L, 0L, 60L),
                     class = c("decorated", "blank", "unclassified", "blank",
                               "unclassified", "unclassified"),
                     comments = c("YAY", "MAU", "IRL", "MPU", "MPU", "BAC"),
                     stringsAsFactors = FALSE)

  if (grouped) {
    base$sample_name <- c(rep("WT", 3), rep("KO", 3))
  }
  base
}


#' Create minimal class_data (UNM + QCF variant)
#'
#' Generates a test data frame mimicking a Guppy/nanopolish pipeline
#' with both UNM and QCF reads, without BAC annotations.
#'
#' @param grouped Logical; if TRUE, adds a `sample_name` column
#'   splitting reads into WT and KO groups.
#'
#' @return A data.frame containing simulated read classification data.
#'
#' @keywords internal
# Guppy/nanopolish pipeline with unmapped reads: has UNM + QCF, no BAC
make_class_data_unm_qcf <- function(grouped = FALSE) {

  base <- data.frame(readname= paste0("read_", 1:7),
                     contig = "beta_gal",
                     polya_length = c(50, 30, 8, 45, 20, 55, 0),
                     qc_tag = c("PASS", "PASS", "PASS", "PASS", "PASS", "ADAPTER", "PASS"),
                     class = c("decorated", "blank", "unclassified", "blank",
                              "unclassified", "unclassified", "unclassified"),
                     comments = c("YAY", "MAU", "IRL", "MPU", "MPU", "QCF", "UNM"),stringsAsFactors = FALSE)

  if (grouped) {
    base$sample_name <- c(rep("WT", 4), rep("KO", 3))
  }
  base
}


#' Create minimal class_data (UNM + BAC variant)
#'
#' Generates a test data frame mimicking a Dorado pipeline
#' with both UNM and BAC reads, without QCF annotations.
#'
#' @param grouped Logical; if TRUE, adds a `sample_name` column
#'   splitting reads into WT and KO groups.
#'
#' @return A data.frame containing simulated read classification data.
#'
#' @keywords internal
# Dorado pipeline with unmapped reads: has UNM + BAC, no QCF
make_class_data_unm_bac <- function(grouped = FALSE) {

  base <- data.frame(readname = paste0("read_", 1:7),
                     contig = "beta_gal",
                     polya_length = c(50, 30, 8, 45, 20, 55, 0),
                     qc_tag = c(60L, 60L, 60L, 60L, 60L, 60L, 0L),
                     class = c("decorated", "blank", "unclassified",
                              "blank","unclassified", "unclassified",
                              "unclassified"),
                     comments = c("YAY", "MAU", "IRL", "MPU", "MPU",
                                 "BAC", "UNM"),
                     stringsAsFactors = FALSE)

  if (grouped) {
    base$sample_name <- c(rep("WT", 4), rep("KO", 3))
  }
  base
}


#' Create class_data with decorated/blank/unclassified classes
#'
#' Generates a test data frame containing balanced examples of
#' "decorated", "blank", and "unclassified" read classes.
#'
#' @param grouped Logical; if TRUE, adds a `sample_name` column
#'   splitting reads into WT and KO groups.
#'
#' @return A data.frame containing simulated read classification data.
#'
#' @keywords internal
# class_data with decorated/blank/unclassified class values (for type="A")
make_class_data_decorated <- function(grouped = FALSE) {
  base <- data.frame(readname= paste0("read_", 1:9),
                     contig = "beta_gal",
                     polya_length = c(50, 30, 8, 45, 20, 55, 60, 35, 70),
                     qc_tag = rep("PASS", 9),
                     class = c("decorated", "decorated", "decorated",
                              "blank", "blank", "blank","unclassified",
                              "unclassified", "unclassified"),
                     comments = c("YAY", "YAY", "YAY","MAU", "MAU",
                                 "MPU","IRL", "QCF", "IRL"),
                     stringsAsFactors = FALSE)

  if (grouped) {
    base$sample_name <- c(rep("WT", 5), rep("KO", 4))
  }
  base
}


# Prevent testthat from creating snapshots and other artifacts
old_opts <- options(
  testthat.default_check_reporter = "silent",
  testthat.use_colour = FALSE,
  warn = -1  # Suppress all warnings during testing
)

# Ensure we restore options when done
withr::defer(options(old_opts), testthat::teardown_env())

# Set working directory to a temporary location for the duration of tests
test_temp_dir <- file.path(tempdir(), "ninetails_tests")
dir.create(test_temp_dir, showWarnings = FALSE, recursive = TRUE)
old_wd <- setwd(test_temp_dir)
withr::defer(setwd(old_wd), testthat::teardown_env())

# Clean up function to remove any stray files
cleanup_test_files <- function() {
  # Remove common plot artifacts
  files_to_remove <- c("Rplots.pdf", "Rplot.pdf", "_snaps")
  for(f in files_to_remove) {
    if(file.exists(f)) unlink(f, recursive = TRUE, force = TRUE)
    # Also check in original directory
    orig_path <- file.path(old_wd, f)
    if(file.exists(orig_path)) unlink(orig_path, recursive = TRUE, force = TRUE)
  }
}

# Run cleanup after all tests
withr::defer(cleanup_test_files(), testthat::teardown_env())

# plot_squiggle_fast5
################################################################################

test_that("plot_squiggle_fast5 correctly parses data & draws a signal plot", {
  empty_tempfile = tempfile()
  nanopolish = system.file('extdata', 'test_data', 'legacy', 'nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary = system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  test_workspace = system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')
  uncalled_workspace= system.file('extdata', 'test_data', 'legacy', 'uncalled_fast5', package = 'ninetails')
  test_basecall_group = 'Basecall_1D_000'
  wrong_basecall_group = 'Basecall_1D_003'

  # wrong readname
  expect_error(plot_squiggle_fast5(readname = "this_is_a_wrong_readname",
                                   nanopolish = nanopolish,
                                   sequencing_summary = sequencing_summary,
                                   workspace = test_workspace,
                                   basecall_group = test_basecall_group,
                                   moves=FALSE,
                                   rescale=FALSE))
  # wrong workspace
  expect_error(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                   nanopolish = nanopolish,
                                   sequencing_summary = sequencing_summary,
                                   workspace = uncalled_workspace,
                                   basecall_group = test_basecall_group,
                                   moves=FALSE,
                                   rescale=FALSE))
  # wrong nanopolish
  expect_error(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                   nanopolish = empty_tempfile,
                                   sequencing_summary = sequencing_summary,
                                   workspace = test_workspace,
                                   basecall_group = test_basecall_group,
                                   moves=FALSE,
                                   rescale=FALSE))
  # wrong seq_sum
  expect_error(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                   nanopolish = nanopolish,
                                   sequencing_summary = empty_tempfile,
                                   workspace = test_workspace,
                                   basecall_group = test_basecall_group,
                                   moves=FALSE,
                                   rescale=FALSE))
  # wrong basecall group
  expect_error(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                   nanopolish = nanopolish,
                                   sequencing_summary = sequencing_summary,
                                   workspace = test_workspace,
                                   basecall_group = wrong_basecall_group,
                                   moves=FALSE,
                                   rescale=FALSE))

})


test_that("plot_squiggle_fast5 returns ggplot with rescale=FALSE, moves=FALSE ", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish <- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(
    plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                        nanopolish = nanopolish,
                        sequencing_summary = sequencing_summary,
                        workspace = workspace,
                        basecall_group = "Basecall_1D_000",
                        moves = FALSE,
                        rescale = FALSE)
    )
  expect_s3_class(result, "gg")
})

test_that("plot_squiggle_fast5 returns ggplot with rescale=FALSE, moves=TRUE (lines 285-304, 307-308)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish<- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(plot_squiggle_fast5(readname= "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                                       nanopolish = nanopolish,
                                                       sequencing_summary = sequencing_summary,
                                                       workspace = workspace,
                                                       basecall_group = "Basecall_1D_000",
                                                       moves = TRUE,
                                                       rescale = FALSE)
  )
  expect_s3_class(result, "gg")
})

test_that("plot_squiggle_fast5 returns ggplot with rescale=TRUE, moves=FALSE (lines 259-283, 309-311)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish<- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                                       nanopolish = nanopolish,
                                                       sequencing_summary = sequencing_summary,
                                                       workspace = workspace,
                                                       basecall_group = "Basecall_1D_000",
                                                       moves = FALSE,
                                                       rescale = TRUE)
  )
  expect_s3_class(result, "gg")
})

test_that("plot_squiggle_fast5 returns ggplot with rescale=TRUE, moves=TRUE (lines 259-283, 307-308)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish<- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(plot_squiggle_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                                       nanopolish = nanopolish,
                                                       sequencing_summary = sequencing_summary,
                                                       workspace = workspace,
                                                       basecall_group = "Basecall_1D_000",
                                                       moves = TRUE,
                                                       rescale = TRUE)
  )
  expect_s3_class(result, "gg")
})


# plot_tail_range_fast5
################################################################################


test_that("plot_squiggle_fast5 errors when readname is missing", {
  nanopolish<- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')
  expect_error(plot_tail_range_fast5(nanopolish = nanopolish,
                                     sequencing_summary = sequencing_summary,
                                     workspace = workspace,
                                     basecall_group = "Basecall_1D_000"),
               "Readname \\[string\\] is missing")
})

test_that("plot_squiggle_fast5 errors when workspace is missing", {
  nanopolish <- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = nanopolish,
                                     sequencing_summary = sequencing_summary,
                                     basecall_group = "Basecall_1D_000"),
               "Directory \\[string\\] with basecalled fast5s is missing")
})



test_that("plot_squiggle_fast5 errors when sequencing_summary is missing", {
  nanopolish <- system.file('extdata', 'test_data', 'legacy', 'nanopolish_output.tsv', package = 'ninetails')
  workspace <- system.file('extdata', 'test_data', 'legacy', 'basecalled_fast5', package = 'ninetails')
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = nanopolish,
                                     workspace = workspace,
                                     basecall_group = "Basecall_1D_000"),
               "Sequencing summary file \\[string\\] is missing")
})

test_that("plot_squiggle_fast5 errors when nanopolish is missing", {
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace<- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     sequencing_summary = sequencing_summary,
                                     workspace= workspace,
                                     basecall_group= "Basecall_1D_000"),
               "Nanopolish polya output \\[string\\] is missing")
})



test_that("plot_tail_range correctly parses data & draws a signal plot", {
  empty_tempfile = tempfile()
  nanopolish = system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary = system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  test_workspace = system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')
  uncalled_workspace= system.file('extdata', 'test_data', 'legacy', 'uncalled_fast5', package = 'ninetails')
  test_basecall_group = 'Basecall_1D_000'
  wrong_basecall_group = 'Basecall_1D_003'

  # wrong readname
  expect_error(plot_tail_range_fast5(readname = "this_is_a_wrong_readname",
                                     nanopolish = nanopolish,
                                     sequencing_summary = sequencing_summary,
                                     workspace = test_workspace,
                                     basecall_group = test_basecall_group,
                                     moves=FALSE,
                                     rescale=FALSE))
  # wrong workspace
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = nanopolish,
                                     sequencing_summary = sequencing_summary,
                                     workspace = uncalled_workspace,
                                     basecall_group = test_basecall_group,
                                     moves=FALSE,
                                     rescale=FALSE))
  # wrong nanopolish
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = empty_tempfile,
                                     sequencing_summary = sequencing_summary,
                                     workspace = test_workspace,
                                     basecall_group = test_basecall_group,
                                     moves=FALSE,
                                     rescale=FALSE))
  # wrong seq_sum
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = nanopolish,
                                     sequencing_summary = empty_tempfile,
                                     workspace = test_workspace,
                                     basecall_group = test_basecall_group,
                                     moves=FALSE,
                                     rescale=FALSE))
  # wrong basecall group
  expect_error(plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                                     nanopolish = nanopolish,
                                     sequencing_summary = sequencing_summary,
                                     workspace = test_workspace,
                                     basecall_group = wrong_basecall_group,
                                     moves=FALSE,
                                     rescale=FALSE))


})


test_that("plot_tail_range_fast5 returns ggplot with rescale=FALSE, moves=FALSE", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish <- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace <- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(
    plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                          nanopolish = nanopolish,
                          sequencing_summary = sequencing_summary,
                          workspace = workspace,
                          basecall_group = "Basecall_1D_000",
                          moves = FALSE,
                          rescale = FALSE)
  )
  expect_s3_class(result, "gg")
})

test_that("plot_tail_range_fast5 returns ggplot with rescale=FALSE, moves=TRUE", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish <- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy', 'sequencing_summary.txt', package = 'ninetails')
  workspace <- system.file('extdata', 'test_data', 'legacy', 'basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(
    plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                          nanopolish = nanopolish,
                          sequencing_summary = sequencing_summary,
                          workspace = workspace,
                          basecall_group = "Basecall_1D_000",
                          moves = TRUE,
      rescale= FALSE
    )
  )
  expect_s3_class(result, "gg")
})

test_that("plot_tail_range_fast5 returns ggplot with rescale=TRUE, moves=FALSE", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish <- system.file('extdata', 'test_data', 'legacy', 'nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy', 'sequencing_summary.txt', package = 'ninetails')
  workspace <- system.file('extdata', 'test_data', 'legacy', 'basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(
    plot_tail_range_fast5(readname = "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                          nanopolish = nanopolish,sequencing_summary = sequencing_summary,
                          workspace = workspace,
                          basecall_group = "Basecall_1D_000",
                          moves = FALSE,
                          rescale = TRUE)
  )
  expect_s3_class(result, "gg")
})

test_that("plot_tail_range_fast5 returns ggplot with rescale=TRUE, moves=TRUE", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("rhdf5")

  nanopolish <- system.file('extdata', 'test_data', 'legacy','nanopolish_output.tsv', package = 'ninetails')
  sequencing_summary <- system.file('extdata', 'test_data', 'legacy','sequencing_summary.txt', package = 'ninetails')
  workspace <- system.file('extdata', 'test_data', 'legacy','basecalled_fast5', package = 'ninetails')

  result <- suppress_plot_warnings(
    plot_tail_range_fast5(readname= "9c11d71e-eaaa-413f-958e-4ca1254e0369",
                          nanopolish= nanopolish,
                          sequencing_summary = sequencing_summary,
                          workspace= workspace,
                          basecall_group= "Basecall_1D_000",
                          moves= TRUE,
                          rescale= TRUE))
  expect_s3_class(result, "gg")
})






# plot_tail_chunk
################################################################################

test_that("plot_tail_chunk validates required arguments", {
  # wrong tail chunk list
  expect_error(plot_tail_chunk(chunk_name = "test_chunk"),
    "List of tail chunks is missing")

  # wrong chunkname
  expect_error(plot_tail_chunk(tail_chunk_list = list()),
    "Chunk_name is missing")

  # wrong input
  expect_error( plot_tail_chunk(chunk_name = "test", tail_chunk_list = "not_a_list"),
    "not a list")
})


test_that("plot_tail_chunk returns ggplot object for valid input", {

  skip_if_not_installed("ggplot2")
  skip_if(!exists("test_tail_chunk_list"), "test_tail_chunk_list not loaded")

  # Get first valid chunk name from the test data
  chunk_names <- unlist(lapply(test_tail_chunk_list, names))
  skip_if(length(chunk_names) == 0, "No chunks in test_tail_chunk_list")

  first_chunk <- chunk_names[1]

  result <- suppress_plot_warnings(plot_tail_chunk(chunk_name = first_chunk,
                                                   tail_chunk_list = test_tail_chunk_list))

  expect_s3_class(result, "gg")
  expect_s3_class(result, "ggplot")
})


# plot_gaf
################################################################################

test_that("plot_gaf validates required arguments", {
  expect_error(plot_gaf(gaf_list = list()),"Gaf_name is missing")
  expect_error(plot_gaf(gaf_name = "test"),"List of GAFs is missing")
  expect_error(plot_gaf(gaf_name = "test", gaf_list = "not_a_list"),"not a list")
})


test_that("plot_gaf validates gaf_name exists in gaf_list", {
  skip_if(!exists("test_gaf_list"), "test_gaf_list not loaded")

  expect_error(plot_gaf(gaf_name = "nonexistent_gaf",
                        gaf_list = test_gaf_list),
               "does not contain provided gaf_name")
})


test_that("plot_gaf returns ggplot object for valid input", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("reshape2")
  skip_if(!exists("test_gaf_list"), "test_gaf_list not loaded")
  skip_if(length(test_gaf_list) == 0, "test_gaf_list is empty")

  first_gaf_name <- names(test_gaf_list)[1]

  result <- suppress_plot_warnings(plot_gaf(gaf_name = first_gaf_name,
                                            gaf_list = test_gaf_list,
                                            save_file = FALSE))

  expect_s3_class(result, "gg")
  expect_s3_class(result, "ggplot")
})


test_that("plot_gaf rejects broken gaf_list structure",{
  skip_if(!exists("gaf_list_broken"), "gaf_list_broken not loaded")
  skip_if(length(gaf_list_broken) == 0, "gaf_list_broken is empty")

  # The broken gaf_list should cause issues during plotting
  # This is chunk with wrong values
  gaf_name <- names(gaf_list_broken)[16]

  # Expecting an error when trying to plot malformed GAF
  expect_error(invisible(print(plot_gaf(gaf_name = gaf_name,
                                        gaf_list = gaf_list_broken,
                                        save_file = FALSE))))
})



# plot_multiple_gaf
################################################################################

test_that("plot_multiple_gaf validates required arguments", {
  expect_error(plot_multiple_gaf(num_cores = 1),"List of GAFs is missing")
  expect_error(plot_multiple_gaf(gaf_list = list()),"Number of declared cores is missing")
  expect_error(plot_multiple_gaf(gaf_list = "not_a_list",num_cores = 1),"not a list")
  expect_error(plot_multiple_gaf(gaf_list = list(a = 1), num_cores = "one"),"must be numeric")
})


test_that("plot_multiple_gaf runs without error for a minimal gaf_list (lines 909-961)", {
  skip_on_ci()
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("foreach")
  skip_if_not_installed("doSNOW")
  skip_if(!exists("test_gaf_list"), "test_gaf_list not loaded")
  skip_if(length(test_gaf_list) == 0, "test_gaf_list is empty")

  # Slice to exactly one element to avoid writing many files
  minimal_gaf_list <- test_gaf_list[1]

  # suppress_plot_warnings redirects cwd to a temp dir, catching the PNG output
  expect_no_error(suppress_plot_warnings(plot_multiple_gaf(
    gaf_list  = minimal_gaf_list,
    num_cores = 1))
  )
})



# plot_class_counts
################################################################################

test_that("plot_class_counts validates required arguments", {
  expect_error(plot_class_counts(),"Class_data is missing")
  expect_error(plot_class_counts(class_data = data.frame()),"Empty data frame")
  expect_error(plot_class_counts(class_data = class_data_single,frequency = "yes"),"Non-boolean")
  expect_error(plot_class_counts(class_data = class_data_single,type = 123),"Non-character")
})


test_that("plot_class_counts returns ggplot for ungrouped data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("class_data_single"), "class_data_single not loaded")

  # Type R - detailed (comments)
  result_r <- suppress_plot_warnings(plot_class_counts(class_data = class_data_single,
                                                       type = "R"))
  expect_s3_class(result_r, "gg")

  # Type N - crude (class)
  result_n <- suppress_plot_warnings(plot_class_counts(class_data = class_data_single,
                                                       type = "N"))
  expect_s3_class(result_n, "gg")
})


test_that("plot_class_counts returns ggplot for grouped data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")

  # With grouping factor and frequency
  result_freq <- suppress_plot_warnings(
    plot_class_counts(class_data = class_data_grouped,
                      grouping_factor = "sample_name",
                      frequency = TRUE,
                      type = "R"))

  expect_s3_class(result_freq, "gg")

  # With grouping factor and counts
  result_count <- suppress_plot_warnings(
    plot_class_counts(class_data = class_data_grouped,
                      grouping_factor = "sample_name",
                      frequency = FALSE,
                      type = "N"))

  expect_s3_class(result_count, "gg")
})


test_that("plot_class_counts handles has_unm && !has_bac (QCF pipeline with unmapped reads)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_unm_qcf(), type = "R"))

  expect_s3_class(result, "gg")
})

test_that("plot_class_counts handles !has_unm && has_bac (Dorado filtered pipeline)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_bac(),type= "R"))
  expect_s3_class(result, "gg")
})

test_that("plot_class_counts handles has_unm && has_bac (Dorado unfiltered)", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_unm_bac(),type= "R"))

  expect_s3_class(result, "gg")
})



test_that("plot_class_counts type='R' grouped with frequency=FALSE returns ggplot ", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data= make_class_data_qcf(grouped = TRUE),
                      grouping_factor  = "sample_name",
                      frequency= FALSE,
                      type= "R"))

  expect_s3_class(result, "gg")
})


test_that("plot_class_counts applies QCF palette when has_bac is FALSE", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  # QCF pipeline data: has_bac is FALSE, so the else branch at 1150-1151 fires
  result <- suppress_plot_warnings(plot_class_counts(class_data = make_class_data_qcf(),type= "R"))
  expect_s3_class(result, "gg")

  # Verify that a QCF-labelled scale was applied by checking the plot is not null
  # (structural inspection of scale internals is too brittle; NULL check is sufficient)
  expect_true(!is.null(result))
})


test_that("plot_class_counts type='N' grouped with frequency=TRUE returns ggplot", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data= make_class_data_qcf(grouped = TRUE),
                      grouping_factor  = "sample_name",
                      frequency= TRUE,
                      type= "N"))

  expect_s3_class(result, "gg")
})


test_that("plot_class_counts type='A' ungrouped returns ggplot", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_decorated(),
      type= "A"))

  expect_s3_class(result, "gg")
})

test_that("plot_class_counts type='A' grouped frequency=FALSE returns ggplot", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_decorated(grouped = TRUE),
                      grouping_factor = "sample_name",
                      frequency = FALSE,
                      type = "A"))

  expect_s3_class(result, "gg")
})

test_that("plot_class_counts type='A' grouped frequency=TRUE returns ggplot", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("forcats")

  result <- suppress_plot_warnings(
    plot_class_counts(class_data = make_class_data_decorated(grouped = TRUE),
                      grouping_factor = "sample_name",
                      frequency = TRUE,
                      type = "A"))

  expect_s3_class(result, "gg")
})

test_that("plot_class_counts errors on unknown type", {
  expect_error(plot_class_counts(class_data = make_class_data_qcf(),
                                 type= "Z"),
               "Wrong type of plot defined")
})



# plot_residue_counts
################################################################################

test_that("plot_residue_counts validates required arguments", {
  expect_error(plot_residue_counts(),"Residue_data dataframe is missing")

  expect_error(plot_residue_counts(residue_data = data.frame()), "Empty data frame")
})


test_that("plot_residue_counts returns ggplot for ungrouped data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")

  # Default (by residue)
  result <- suppress_plot_warnings(plot_residue_counts(residue_data = residue_data_single))
  expect_s3_class(result, "gg")

  # By read
  result_by_read <- suppress_plot_warnings(
    plot_residue_counts(residue_data = residue_data_single,
                        by_read = TRUE))

  expect_s3_class(result_by_read, "gg")
})


test_that("plot_residue_counts returns ggplot for grouped data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if_not_installed("tidyr")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")

  # With grouping factor and frequency
  result_freq <- suppress_plot_warnings(plot_residue_counts(
    residue_data = residue_data_grouped,
    grouping_factor = "group",
    frequency = TRUE))

  expect_s3_class(result_freq, "gg")

  # With grouping factor and counts
  result_count <- suppress_plot_warnings(
    plot_residue_counts(residue_data = residue_data_grouped,
                        grouping_factor = "group",
                        frequency = FALSE))

  expect_s3_class(result_count, "gg")
})


# plot_nanopolish_qc
################################################################################

test_that("plot_nanopolish_qc validates required arguments", {
  expect_error(plot_nanopolish_qc(),"Nanopolish processing info is missing")

  expect_error(plot_nanopolish_qc(processing_info = data.frame()),"Empty data frame")

  # Missing required columns
  bad_df <- data.frame(a = 1, b = 2)
  expect_error(plot_nanopolish_qc(processing_info = bad_df),"qc_tag column is missing")

  # Wrong type for frequency
  good_df <- create_test_processing_info(grouped = FALSE)
  expect_error(plot_nanopolish_qc(processing_info = good_df,frequency = "yes"),"Non-boolean")

})


test_that("plot_nanopolish_qc returns ggplot for ungrouped data", {
  skip_if_not_installed("ggplot2")

  processing_info <- create_test_processing_info(grouped = FALSE)

  result <- suppress_plot_warnings(plot_nanopolish_qc(processing_info = processing_info,
                                                      frequency = TRUE))

  expect_s3_class(result, "gg")

  result_count <- suppress_plot_warnings(plot_nanopolish_qc(processing_info = processing_info,
                                                            frequency = FALSE))

  expect_s3_class(result_count, "gg")
})


test_that("plot_nanopolish_qc returns ggplot for grouped data", {
  skip_if_not_installed("ggplot2")

  processing_info <- create_test_processing_info(grouped = TRUE)

  result_freq <- suppress_plot_warnings(plot_nanopolish_qc(processing_info = processing_info,
                                                           frequency = TRUE))

  expect_s3_class(result_freq, "gg")

  result_count <- suppress_plot_warnings(plot_nanopolish_qc(processing_info = processing_info,
                                                            frequency = FALSE))

  expect_s3_class(result_count, "gg")
})



# plot_tail_distribution
################################################################################

test_that("plot_tail_distribution validates required arguments", {
  expect_error(plot_tail_distribution(),"Ninetails data are missing")

  expect_error(plot_tail_distribution(input_data = residue_data_single,
                                      variable_to_plot = 123),"must be a string")
})


test_that("plot_tail_distribution validates grouping_factor exists", {
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")

  expect_error(plot_tail_distribution(
    input_data = residue_data_single,
    grouping_factor = "nonexistent_column"),"is not a column")
})


test_that("plot_tail_distribution returns ggplot for polya_length", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("merged_nonA_char"), "merged_nonA_char not loaded")

  result <- suppress_plot_warnings(plot_tail_distribution(input_data = merged_nonA_char,
                                                          variable_to_plot = "polya_length",
                                                          grouping_factor = "group",
                                                          max_length = 200,
                                                          ndensity = TRUE,
                                                          title = TRUE))

  expect_s3_class(result, "gg")
})


test_that("plot_tail_distribution returns ggplot for est_nonA_pos", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")

  result <- suppress_plot_warnings(plot_tail_distribution(input_data = residue_data_grouped,
                                                          variable_to_plot = "est_nonA_pos",
                                                          grouping_factor = "group",
                                                          max_length = 150,
                                                          ndensity = TRUE,
                                                          title = FALSE))

  expect_s3_class(result, "gg")
})


test_that("plot_tail_distribution shows central tendency measures", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("dplyr")
  skip_if(!exists("merged_nonA_char"), "merged_nonA_char not loaded")

  # Test median
  result_median <- suppress_plot_warnings(
    plot_tail_distribution(
      input_data = merged_nonA_char,
      variable_to_plot = "polya_length",
      grouping_factor = "group",
      value_to_show = "median"
    )
  )
  expect_s3_class(result_median, "gg")

  # Test mean
  result_mean <- suppress_plot_warnings(plot_tail_distribution(input_data = merged_nonA_char,
                                                               variable_to_plot = "polya_length",
                                                               grouping_factor = "group",
                                                               value_to_show = "mean"))

  expect_s3_class(result_mean, "gg")

  # Test mode
  result_mode <- suppress_plot_warnings(plot_tail_distribution(input_data = merged_nonA_char,
                                                               variable_to_plot = "polya_length",
                                                               grouping_factor = "group",
                                                               value_to_show = "mode"))

  expect_s3_class(result_mode, "gg")
})


test_that("plot_tail_distribution falls back to variable name for custom variable_to_plot", {
  skip_if_not_installed("ggplot2")
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")
  # Add a custom numeric column so the plot engine has something to map
  test_data <- residue_data_single
  test_data$custom_score <- stats::runif(nrow(test_data), 0, 100)

  result <- suppress_plot_warnings(plot_tail_distribution(input_data = test_data,
                                                          variable_to_plot = "custom_score"))

  expect_s3_class(result, "gg")
})


test_that("plot_tail_distribution without grouping_factor returns ggplot", {
  skip_if_not_installed("ggplot2")
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")

  # Default grouping_factor = NA triggers the else branch at 1750-1754
  result <- suppress_plot_warnings(plot_tail_distribution(input_data = residue_data_single,
                                                          variable_to_plot = "polya_length"))
  expect_s3_class(result, "gg")
})


test_that("plot_tail_distribution errors on invalid value_to_show", {
  skip_if(!exists("merged_nonA_char"), "merged_nonA_char not loaded")

  # value_to_show must be non-NA and not in {median, mean, mode} to trigger stop
  expect_error(plot_tail_distribution(input_data = merged_nonA_char,
                                      variable_to_plot = "polya_length",
                                      grouping_factor = "group",
                                      value_to_show = "geometric_mean"),
               "Wrong value_to_show specified")
})




# plot_panel_characteristics
################################################################################

test_that("plot_panel_characteristics returns plot with class_data", {

  skip_if_not_installed("ggplot2")
  skip_if_not_installed("patchwork")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")

  # overwrite multiple groups with one group
  class_dat <- class_data_grouped
  res_dat <- residue_data_grouped

  class_dat$group <- "WT"
  res_dat$group <- "WT"

  # Use grouped data which has required 'group' column
  result <- suppress_plot_warnings(
    plot_panel_characteristics(input_residue_data = res_dat,
                               input_class_data = class_dat,
                               type = "default",
                               max_length = 200,
                               direction_5_prime = TRUE))

  expect_true(!is.null(result))
})


test_that("plot_panel_characteristics returns plot with merged data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("patchwork")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("merged_nonA_num"), "merged_nonA_num not loaded")

  # overwrite multiple groups with one group
  merged_nonA <- merged_nonA_num
  res_dat <- residue_data_grouped

  merged_nonA$group <- "WT"
  res_dat$group <- "WT"

  # Use grouped residue data which has required 'group' column
  result <- suppress_plot_warnings(
    plot_panel_characteristics(input_residue_data = res_dat,
                               input_merged_nonA_tables_data = merged_nonA,
                               type = "default",
                               max_length = 200))

  expect_true(!is.null(result))
})




test_that("plot_panel_characteristics errors when multiple groups present (class_data)", {

  skip_if_not_installed("ggplot2")
  skip_if_not_installed("patchwork")

  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")

  # Use original grouped data (contains multiple groups)
  expect_error(suppress_plot_warnings(
    plot_panel_characteristics(
      input_residue_data = residue_data_grouped,
      input_class_data = class_data_grouped,
      type = "default",
      max_length = 200,
      direction_5_prime = TRUE)))
})



test_that("plot_panel_characteristics errors when multiple groups present (merged_nonA)", {

  skip_if_not_installed("ggplot2")
  skip_if_not_installed("patchwork")

  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("merged_nonA_num"), "merged_nonA_num not loaded")

  # Use original grouped data (contains multiple groups)
  expect_error(suppress_plot_warnings(
    plot_panel_characteristics(
      input_residue_data = residue_data_grouped,
      input_merged_nonA_tables_data = merged_nonA_num,
      type = "default",
      max_length = 200,
      direction_5_prime = TRUE)))
})


test_that("plot_panel_characteristics errors when both optional inputs are NULL", {
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")

  single_res <- residue_data_grouped
  single_res$group <- "WT"

  expect_error(
    plot_panel_characteristics(
      input_residue_data = single_res,
      input_class_data = NULL,
      input_merged_nonA_tables_data = NULL),
    "At least one dataframe should be provided")
})

test_that("plot_panel_characteristics errors when both optional inputs are supplied", {
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")
  skip_if(!exists("merged_nonA_num"), "merged_nonA_num not loaded")

  single_res <- residue_data_grouped; single_res$group <- "WT"
  single_class <- class_data_grouped; single_class$group <- "WT"
  single_merged <- merged_nonA_num; single_merged$group <- "WT"

  expect_error(
    plot_panel_characteristics(
      input_residue_data = single_res,
      input_class_data = single_class,
      input_merged_nonA_tables_data = single_merged),"Only one dataframe should be provided")
})


test_that("plot_panel_characteristics errors on multi-group input_class_data", {
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"),  "class_data_grouped not loaded")

  single_res <- residue_data_grouped  # make single-group
  single_res$group <- "WT"

  # class_data retains multiple groups
  multi_class <- class_data_grouped

  expect_error(plot_panel_characteristics(input_residue_data = single_res,
                                          input_class_data = multi_class),
               "Multiple groups detected in input_class_data")
})


test_that("plot_panel_characteristics errors on multi-group input_merged_nonA_tables_data", {
  # residue_data must be single-group to bypass the residue guard; then the
  # merged_nonA guard at 2055-2068 fires, covering lines 2058-2066.
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("merged_nonA_num"), "merged_nonA_num not loaded")

  single_res <- residue_data_grouped
  single_res$group <- "WT"

  # merged_nonA_num retains multiple groups
  multi_merged <- merged_nonA_num

  expect_error(plot_panel_characteristics(input_residue_data= single_res,
                                          input_merged_nonA_tables_data = multi_merged),
               "Multiple groups detected in input_merged_nonA_tables_data")
})










# plot_rug_density
################################################################################

test_that("plot_rug_density validates base argument", {
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")

  expect_error(plot_rug_density(residue_data = residue_data_single,
                                base = "A",
                                max_length = 100),"Wrong base")

  expect_error(plot_rug_density(residue_data = residue_data_single,
                                base = "X",
                                max_length = 100),"Wrong base")
})


test_that("plot_rug_density returns plot-like object for valid bases", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("cowplot")
  skip_if_not_installed("dplyr")
  skip_if(!exists("residue_data_single"), "residue_data_single not loaded")

  # Test C
  result_c <- suppress_plot_warnings(
    plot_rug_density(residue_data = residue_data_single,
                     base = "C",
                     max_length = 150))

  # cowplot returns different class, check it's not null
  expect_true(!is.null(result_c))

  # Test G
  result_g <- suppress_plot_warnings(
    plot_rug_density(residue_data = residue_data_single,
                     base = "G",
                     max_length = 150))

  expect_true(!is.null(result_g))

  # Test U
  result_u <- suppress_plot_warnings(
    plot_rug_density(residue_data = residue_data_single,
                     base = "U",
                     max_length = 150))

  expect_true(!is.null(result_u))
})


test_that("plot_rug_density works with grouped residue data", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("cowplot")
  skip_if_not_installed("dplyr")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")

  result <- suppress_plot_warnings(
    plot_rug_density(residue_data = residue_data_grouped,
                     base = "G",
                     max_length = 150))

  expect_true(!is.null(result))
})


test_that("plot_panel_characteristics returns plot with type = 'moderna'", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("patchwork")
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")

  single_res <- residue_data_grouped; single_res$group <- "WT"
  single_class <- class_data_grouped; single_class$group <- "WT"

  result <- suppress_plot_warnings(
    plot_panel_characteristics(input_residue_data = single_res,
                               input_class_data = single_class,
                               type = "moderna",
                               max_length = 200,
                               direction_5_prime  = TRUE))

  expect_true(!is.null(result))
})


test_that("plot_panel_characteristics errors on unknown type ", {
  skip_if(!exists("residue_data_grouped"), "residue_data_grouped not loaded")
  skip_if(!exists("class_data_grouped"), "class_data_grouped not loaded")

  single_res <- residue_data_grouped; single_res$group <- "WT"
  single_class <- class_data_grouped; single_class$group <- "WT"

  expect_error(suppress_plot_warnings(plot_panel_characteristics(
    input_residue_data = single_res,
    input_class_data = single_class,
    type = "unknown_type")
    ),"Unknown type of data defined")
})


# plot_nonA_abundance
################################################################################

# Helper: Create residue data with reads having 1, 2, and 3+ non-A residues
create_residue_data_for_abundance <- function() {
  data.frame(
    readname = c(
      # Single non-A reads
      "read_single_1", "read_single_2", "read_single_3",
      # Two non-A reads (same readname appears twice)
      "read_two_1", "read_two_1","read_two_2", "read_two_2",
      # Three+ non-A reads (same readname appears 3+ times)
      "read_more_1", "read_more_1", "read_more_1","read_more_2",
      "read_more_2", "read_more_2", "read_more_2"),
    contig = rep("beta_gal", 14),
    prediction = c("G", "C", "U","G", "C","U", "G","G", "C", "U","G", "C", "U", "G"),
    est_nonA_pos = c(30, 45, 60,20, 50,25, 55,10, 30, 50,15, 35, 55, 75),
    polya_length = c(100, 120, 80,90, 90,110, 110,130, 130, 130,150, 150, 150, 150),
    qc_tag = rep(60, 14),
    sample_name = c(rep("WT_1", 7),rep("KO_1", 7)),
    group = c(rep("WT", 7),rep("KO", 7)),
    stringsAsFactors = FALSE)
}


test_that("plot_nonA_abundance returns ggplot object", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("tidyr")
  skip_if_not_installed("dplyr")

  # Use helper data that has single, two, and more categories
  test_residue_data <- create_residue_data_for_abundance()

  result <- suppress_plot_warnings(
    ninetails::plot_nonA_abundance(residue_data = test_residue_data,
                                   grouping_factor = "sample_name"))

  expect_s3_class(result, "gg")
  expect_s3_class(result, "ggplot")
})


test_that("plot_nonA_abundance works with group column", {
  skip_if_not_installed("ggplot2")
  skip_if_not_installed("tidyr")
  skip_if_not_installed("dplyr")

  # Use helper data that has single, two, and more categories
  test_residue_data <- create_residue_data_for_abundance()

  result <- suppress_plot_warnings(
    ninetails::plot_nonA_abundance(residue_data = test_residue_data,
                                   grouping_factor = "group"))

  expect_s3_class(result, "gg")
})


test_that("plot_nonA_abundance errors when residue_data is missing", {
  expect_error(plot_nonA_abundance(),"Residue_data is missing")
})

test_that("plot_nonA_abundance errors on empty residue_data data frame", {
  expect_error(plot_nonA_abundance(residue_data = data.frame()),
               "Empty data frame provided as an input \\(residue_data\\)"
  )
})
